### ISSUE TITLE
THREE.Object3D.add: object not an instance of THREE.Object3D

### ISSUE THREAD

**Issue by jmpp** [AVGP/h2g2three#2]
Hi!

I can't manage to get the editor working after have forked the projet and run `npm install` and `npm run dev` ... I can't see the result of any example by pressing `Alt+Return`. I constantly get this error : 

> THREE.Object3D.add: object not an instance of THREE.Object3D. T…E.Mesh {uuid: "04C1D417-7BF1-4350-8011-28806719B145", name: "", type: "Mesh", parent: undefined, children: Array[0]…}

![Imgur](http://i.imgur.com/HANBRIj.png)

Also, I dont know why I'm getting a WebGLRenderer 71 whereas you're running a WebglRenderer 69 on your online version : http://avgp.github.io/h2g2three/.
Maybe it's the problem, but I can't see how to fix that :/ Any idea ?

**Comment by AVGP** [comment]
Oh sorry, that's a mixup in versions of the dependencies. Will fix it when I have some time to do so, probably tonight

**Comment by jmpp** [comment]
No problem. I'll wait ;) Thanks.

**Comment by AVGP** [comment]
@jmpp did the fix resolve the problem for you?

Keep in mind you may need to delete the `node_modules` folder and do `npm i` again

**Comment by jmpp** [comment]
Sorry, yes it does. Thanks you very much :)

I'm currently working on how to implement codemirror as the default editor. I'll do a pull request when I'll succeed to :)

**Comment by AVGP** [comment]
Cool! Let me know if you're getting somewhere with that - it would be so great!

**Comment by jmpp** [comment]
Yep, I will, no problem ;)

**Comment by AVGP** [comment]
How's the Codemirror integration coming along? Anything I can help you with?

**Comment by jmpp** [comment]
In fact I've encountered a problem with the instantiation of codemirror, as it needs a textarea DOM object appended to the body, and your initial textarea is used as an object 3-D in a CSS rendered.
Couldn't fix that for the moment, and I'm a bit busy these time. Maybe I'll give it another try later :)
